
-- ----------------------------
-- Insert records for Company
-- ----------------------------
INSERT INTO COMPANY (name, address, phone) VALUES
('SCF DELUXE','El doral',87781040);

-- ----------------------------
-- Insert records for Business_Unit
-- ----------------------------
INSERT INTO Business_Unit (company_id, name, address, phone) VALUES
(1,'San Rafael','San Rafael',87781040);

-- ----------------------------
-- Insert records for Client
-- ----------------------------
INSERT INTO CLIENT (business_unit_id, first_name, last_name) VALUES
(1,'Julia Lorena','Lopez Sanchez'),
(1,'Dayana de los Angeles','Marchena Guillen'),
(1,'Maria de los Angeles','Guillen Rocha'),
(1,'Ana Maricela','Ramirez Solis'),
(1,'Argelia Maria','Sanchez Cruz'),
(1,'Karla Yorlenis','Gutierrez Calero'),
(1,'Juan Jose','Espinoza Martinez'),
(1,'Eliett Maryina','Velasquez Espinoza'),
(1,'Alex de los Reyes','Mojica Espinoza'),
(1,'Irayda Francis','Mendez Barahona'),
(1,'Ana Marcela','Mercado Mojica'),
(1,'Oscar Antonio','Areas Alvarez'),
(1,'Julio Cesar','Solorzano Vanega'),
(1,'Zenelia de los Angeles','Guadamuz Hernandez'),
(1,'Alejandro Enrique','Cruz Quiroz'),
(1,'Katherine Dayana','Rodriguez Ramirez'),
(1,'Maria Elena','Herrera Arce'),
(1,'Noel','Gudiel'),
(1,'Raquel Thamara','Rocha Palacio'),
(1,'Jenny Tamara','Guerrero Guerrero'),
(1,'Madai del Socorro','Navarro Zeledon'),
(1,'Antonio Taurino','Mercado Hernandez'),
(1,'Belia Nadeska','Mercado Mojica'),
(1,'Perla Marina','Sanchez Silva'),
(1,'Karla Patricia','Fierro Flores'),
(1,'Gabriela de la Concepcion','Aguirre Porras'),
(1,'Martha Sushaira','Cabrera Gutierrez'),
(1,'Yahoska del Rosario','Estrada Gutierrez'),
(1,'Milagro Calero','Espinoza'),
(1,'Jose Ali','Tellez Prado'),
(1,'Ana Josseling','Rojas Garcia'),
(1,'Jose Daniel','Tenorio Araya'),
(1,'Bayron Antonio','Mendieta'),
(1,'Loyda Isabel','Gomez Mojica'),
(1,'Melisa Lladira','Sanchez Calero'),
(1,'Yamali del Carmen','Puerto Sanchez'),
(1,'Carlota de los Angeles','Silva Garcia'),
(1,'Juana Teodora','Aragon Hernandez'),
(1,'Alma Nidia','Acevedo Calero'),
(1,'Martha Jovanis','Sanchez Alegria'),
(1,'Edgard Antonio','Gomez Nuñez'),
(1,'Marcos Antonio','Bordas Cailan'),
(1,'Ana Lorena','Fuentes Guitierrez'),
(1,'Marlinda Isabel','Gutierrez'),
(1,'Ana Patricia','Mendeza Salgado'),
(1,'Rosa Isabel','Navarro Gutierrez'),
(1,'Dennis Omar','Gomez Rizo'),
(1,'Scarleth Vanessa','Vallecillo Espinoza'),
(1,'Amilcar Alonzo','Gomez Nuñez'),
(1,'Kenia Roxana','Martinez Icabalceta'),
(1,'Norma Isabel','Manzanarez Aburto'),
(1,'Eddy Rodolfo','Bojorge Moya'),
(1,'Maria del Carmen','Sanchez Rocha'),
(1,'Urania del Socorro','Cordoza Rodriguez'),
(1,'Zayda Elizabeth','Reyes Gomez'),
(1,'Gissela de los Angeles','Garcia Espinoza'),
(1,'Ada Jobanela','Escoto Cerda'),
(1,'Maria Esperanza','Solorzano Romero'),
(1,'Maria Elena','Cruz Lopez'),
(1,'Ruth Raquel','Palacio Cruz'),
(1,'Ada Luz','Martinez Garcia'),
(1,'Lucia del Carmen','Vargas Muños'),
(1,'Deyling Gabriela','Gutierrez'),
(1,'Juana Jacinta','Salazar Garcia'),
(1,'Cesar Agusto','Gomez Baltodano'),
(1,'Cristhian Manuel','Calero Jarquin'),
(1,'Rosa Maria','Valverde Gago'),
(1,'Celso Abraham','Rodriguez Canales'),
(1,'Dominga del Socorro','Morales Diaz'),
(1,'Miguel Angel','Rodriguez Perez'),
(1,'Carlos Bismark','Gaitan Lopez'),
(1,'Gabriela de la Concepcion','Espinoza Gutierrez'),
(1,'Daniel Humberto','Guerrero Garcia'),
(1,'Jose Manuel','Guevara Rodriguez'),
(1,'Maria Jose','Castro Sanchez'),
(1,'Beatriz Leonor','Jimenez Vado'),
(1,'Omar Teodoro','Herrera Cardoza'),
(1,'Betania Eloaisa','Alonso Estrada'),
(1,'Delfa Senobia','Castillo Valverde'),
(1,'Martha Maribel','Espinoza Artola'),
(1,'Carlos Alberto','Navarretes Flores'),
(1,'Jefry Josue','Cabrera Espinoza'),
(1,'Gladys del Carmen','Gomez Mejia'),
(1,'Juan Jose','Espinoza Martinez'),
(1,'Keren Alieska','Rizo Rizo'),
(1,'Maria Jose','Sanchez Gutierrez'),
(1,'Martha Lorena','Rivera Sanchez'),
(1,'Maria Francisca','Rodriguez Quiroz'),
(1,'Nora del Carmen','Rodriguez'),
(1,'William Antonio','Jimenez Martinez'),
(1,'Juan Manuel','Salgado Gaitan'),
(1,'Meyling del Socorro','Velasquez Hernandez'),
(1,'Jose Carlos','Gomez Martinez'),
(1,'Luis Antonio','Gutierrez Luquez'),
(1,'Yamali del Carmen','Puerto Mercado'),
(1,'Allan Henrry','Galan Calero'),
(1,'Juan Carlos','Mercado Calero'),
(1,'Christian Eduardo','Martinez Aguirrez'),
(1,'Yennifer Georgina','Bendaña Carcache'),
(1,'Felix Ruben','Ramirez Gutierrez'),
(1,'Juan Pablo','Maliaños Lopez'),
(1,'Yessenia Yorleny','Mercado Martinez'),
(1,'Arely Isabel','Lara Espinoza'),
(1,'Karla Vaneza','Lopez Martinez'),
(1,'Maribel del Socorro','Estrada Montenegro'),
(1,'Maria Nery','Rivera Martinez'),
(1,'Ana Lucia','Cruz Hurtado'),
(1,'Ermin','Larios Flores'),
(1,'Lucelia Lisseth','Blas Rosales'),
(1,'Heysell Amparo','Zuniga Cruz'),
(1,'Nilson Dolores','Castillo Baltodano'),
(1,'Xochild Danelia','Zeledon Campos'),
(1,'Noelia del','Carmen Gutierrez'),
(1,'Holman Jeronimo','Blas Areas'),
(1,'Deybis Jairo','Quintero Carballo'),
(1,'Sergio Gabriel','Mendoza Sanchez'),
(1,'Keyla Priscila','Gutierrez Rocha'),
(1,'Juana Manuela','Gaitan Sequeira'),
(1,'Ariel Salomon','Rocha Palacios'),
(1,'Mauricio Anastacio','Gutierrez Mendoza'),
(1,'Taiz Rafaela','Baca Espinoza'),
(1,'Socorro del','Carmen Martinez'),
(1,'Bayardo Antonio','Marchena Guillen'),
(1,'Delia Valeska','Mercado Mojica'),
(1,'Keren Veronica','Mendieta Mojica'),
(1,'Marcos Aurelio','Cruz Palacios'),
(1,'Panfilo de Jesus','Romero Vargas'),
(1,'Alisson Denit','Espinoza Rocha'),
(1,'Celia','Mojica Mendez'),
(1,'Ludary Maythe','Doña Guerrero'),
(1,'Mayner Ernaldo','Gutierrez Espinoza'),
(1,'Domingo Antonio','Rocha Jimenez');

